apiVersion: v1
kind: ServiceAccount
metadata:
  name: supervisor
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: coordinator
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["get", "watch", "list", create]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: coord-role-binding
subjects:
- kind: ServiceAccount
  name: supervisor
  namespace: default
roleRef:
  kind: ClusterRole
  name: coordinator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: super
  name: super
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: super
  template:
    metadata:
      labels:
        run: super
    spec:
      containers:
      - image: supervisor:latest
        args:
          - "--worker-image=nginx"
          - "--namespace=default"
        imagePullPolicy: Never
        name: super
      serviceAccount: "supervisor"